name: Linux Ubuntu x64/arm64

on: [push]

jobs:
    build-ubuntu:
        strategy:
            matrix:
                qt_version_major: [5, 6]
                os: [ubuntu-latest, ubuntu-24.04-arm]

        runs-on: ${{matrix.os}}
        name: build-${{matrix.os}}-qt${{matrix.qt_version_major}}

        steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Update all package informations
          run: |
              sudo apt-get -y update

        - name: Install Qt${{matrix.qt_version_major}}
          run: |
              if [[ ${{matrix.qt_version_major}} == "5" ]]; then
                  sudo apt-get -y install qtbase5-dev libqt5svg5-dev
              elif [[ ${{matrix.qt_version_major}} == "6" ]]; then
                  sudo apt-get -y install qt6-base-dev qt6-svg-dev libxcb-cursor0
              fi

        - name: Install OpenCascade
          run: |
              sudo apt-get -y install libocct-data-exchange-dev libocct-draw-dev occt-misc
              sudo apt-get -y install libtbb-dev
              sudo apt-get -y install libxi-dev

        - name: Install Assimp
          run: |
              sudo apt-get -y install libassimp-dev

        - name: Build
          run: |
              mkdir ${{github.workspace}}/build
              cd ${{github.workspace}}/build
              cmake --version
              cmake .. \
                    -DMayo_BuildTests=ON \
                    -DMayo_BuildPluginAssimp=ON
              cmake --build . \
                    --config Release \
                    --parallel `nproc`

        - name: Execute Unit Tests
          working-directory: ${{github.workspace}}/build
          env:
              DISPLAY: :0
          run: |
              # Install french locale for testing case
              echo "fr_FR ISO-8859-15" | sudo tee -a /etc/locale.gen
              sudo locale-gen
              localectl list-locales
              # Start X11 display server
              Xvfb $DISPLAY -screen 0 1280x1024x24 &
              sleep 5s
              # Run tests
              ./mayo --runtests
